# Generated by Django 3.1.7 on 2021-04-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210419_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
