# Generated by Django 3.1.7 on 2021-05-01 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_win', to='auctions.listing'),
        ),
    ]
