# Generated by Django 3.1.7 on 2021-05-01 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_winner_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='hs_bid_currency',
        ),
        migrations.AlterField(
            model_name='winner',
            name='hs_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winning_bid', to='auctions.bid'),
        ),
    ]
