# Generated by Django 3.1.7 on 2021-05-01 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210501_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='hs_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_bid', to='auctions.bid'),
        ),
    ]
