# Generated by Django 3.1.7 on 2021-05-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210501_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='listing',
        ),
    ]
